name: ai_music_studio_app
description: "Kenny's Music Studio - Flutter App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  just_audio: ^0.9.40
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
